In [2]:
pip install sdv sdmetrics

Collecting sdv
  Downloading sdv-1.37.0-py3-none-any.whl.metadata (14 kB)
Collecting sdmetrics
  Downloading sdmetrics-0.28.0-py3-none-any.whl.metadata (9.9 kB)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Downloading boto3-1.43.23-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Downloading botocore-1.43.23-py3-none-any.whl.metadata (5.6 kB)
Collecting cloudpickle>=2.1.0 (from sdv)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting graphviz>=0.13.2 (from sdv)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.24.0 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from sdv) (2.4.4)
Requirement already satisfied: pandas<3,>=1.5.0 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from sdv) (2.3.3)
Requirement already satisfied: tqdm>=4.29 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from sdv) (4.67.3)
Collecting copulas>=0.12.1 (from sdv)
  Downloading copulas-0.14.1-py3-none-any.whl.metadata (9.7 kB)
Collecting ctgan>=0.11.1 (from sdv)
  Downloading ctgan-0.12.1-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Downloading deepecho-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting rdt>=1.18.2 (from sdv)
  Downloading rdt-1.21.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: platformdirs>=4.0 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from sdv) (4.9.4)
Requirement already satisfied: pyyaml>=6.0.1 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from sdv) (6.0.3)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0.0,>=1.28->sdv)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.19.0,>=0.18.0 (from boto3<2.0.0,>=1.28->sdv)
  Downloading s3transfer-0.18.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.6.3)
Requirement already satisfied: pytz>=2020.1 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from pandas<3,>=1.5.0->sdv) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from pandas<3,>=1.5.0->sdv) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Collecting scikit-learn>=1.1.3 (from sdmetrics)
  Downloading scikit_learn-1.9.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: scipy>=1.9.2 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from sdmetrics) (1.17.1)
Collecting plotly>=5.19.0 (from sdmetrics)
  Downloading plotly-6.8.0-py3-none-any.whl.metadata (9.0 kB)
Collecting torch>=2.0.0 (from ctgan>=0.11.1->sdv)
  Downloading torch-2.12.0-cp311-cp311-win_amd64.whl.metadata (31 kB)
Collecting narwhals>=1.15.1 (from plotly>=5.19.0->sdmetrics)
  Downloading narwhals-2.22.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from plotly>=5.19.0->sdmetrics) (26.0)
Requirement already satisfied: Faker!=37.11.0,>=17 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from rdt>=1.18.2->sdv) (40.21.0)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from scikit-learn>=1.1.3->sdmetrics) (1.5.3)
Collecting threadpoolctl>=3.5.0 (from scikit-learn>=1.1.3->sdmetrics)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting filelock (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Downloading filelock-3.29.1-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (4.15.0)
Collecting setuptools<82 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (3.1.6)
Collecting fsspec>=0.8.5 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Downloading fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from tqdm>=4.29->sdv) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages (from jinja2->torch>=2.0.0->ctgan>=0.11.1->sdv) (3.0.2)
Downloading sdv-1.37.0-py3-none-any.whl (206 kB)
Downloading boto3-1.43.23-py3-none-any.whl (140 kB)
Downloading botocore-1.43.23-py3-none-any.whl (15.1 MB)
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   - -------------------------------------- 0.5/15.1 MB 85.6 kB/s eta 0:02:51
   -- ------------------------------------- 0.8/15.1 MB 95.3 kB/s eta 0:02:31
   -- ------------------------------------- 0.8/15.1 MB 95.3 kB/s eta 0:02:31
   -- ------------------------------------- 0.8/15.1 MB 95.3 kB/s eta 0:02:31
   -- ------------------------------------- 0.8/15.1 MB 95.3 kB/s eta 0:02:31
   -- ------------------------------------- 0.8/15.1 MB 95.3 kB/s eta 0:02:31
   -- ------------------------------------- 0.8/15.1 MB 95.3 kB/s eta 0:02:31
   -- ------------------------------------- 0.8/15.1 MB 95.3 kB/s eta 0:02:31
   -- ------------------------------------- 0.8/15.1 MB 95.3 kB/s eta 0:02:31
   -- ------------------------------------- 1.0/15.1 MB 110.1 kB/s eta 0:02:09
   -- ------------------------------------- 1.0/15.1 MB 110.1 kB/s eta 0:02:09
   -- ------------------------------------- 1.0/15.1 MB 110.1 kB/s eta 0:02:09
   -- ------------------------------------- 1.0/15.1 MB 110.1 kB/s eta 0:02:09
   -- ------------------------------------- 1.0/15.1 MB 110.1 kB/s eta 0:02:09
   -- ------------------------------------- 1.0/15.1 MB 110.1 kB/s eta 0:02:09
   --- ------------------------------------ 1.3/15.1 MB 125.4 kB/s eta 0:01:51
   --- ------------------------------------ 1.3/15.1 MB 125.4 kB/s eta 0:01:51
   --- ------------------------------------ 1.3/15.1 MB 125.4 kB/s eta 0:01:51
   --- ------------------------------------ 1.3/15.1 MB 125.4 kB/s eta 0:01:51
   --- ------------------------------------ 1.3/15.1 MB 125.4 kB/s eta 0:01:51
   --- ------------------------------------ 1.3/15.1 MB 125.4 kB/s eta 0:01:51
   --- ------------------------------------ 1.3/15.1 MB 125.4 kB/s eta 0:01:51
   ---- ----------------------------------- 1.6/15.1 MB 133.6 kB/s eta 0:01:42
   ---- ----------------------------------- 1.6/15.1 MB 133.6 kB/s eta 0:01:42
   ---- ----------------------------------- 1.6/15.1 MB 133.6 kB/s eta 0:01:42
   ---- ----------------------------------- 1.6/15.1 MB 133.6 kB/s eta 0:01:42
   ---- ----------------------------------- 1.6/15.1 MB 133.6 kB/s eta 0:01:42
   ---- ----------------------------------- 1.6/15.1 MB 133.6 kB/s eta 0:01:42
   ---- ----------------------------------- 1.6/15.1 MB 133.6 kB/s eta 0:01:42
   ---- ----------------------------------- 1.8/15.1 MB 138.7 kB/s eta 0:01:37
   ---- ----------------------------------- 1.8/15.1 MB 138.7 kB/s eta 0:01:37
   ---- ----------------------------------- 1.8/15.1 MB 138.7 kB/s eta 0:01:37
   ---- ----------------------------------- 1.8/15.1 MB 138.7 kB/s eta 0:01:37
   ---- ----------------------------------- 1.8/15.1 MB 138.7 kB/s eta 0:01:37
   ---- ----------------------------------- 1.8/15.1 MB 138.7 kB/s eta 0:01:37
   ---- ----------------------------------- 1.8/15.1 MB 138.7 kB/s eta 0:01:37
   ---- ----------------------------------- 1.8/15.1 MB 138.7 kB/s eta 0:01:37
   ---- ----------------------------------- 1.8/15.1 MB 138.7 kB/s eta 0:01:37
   ----- ---------------------------------- 2.1/15.1 MB 140.3 kB/s eta 0:01:34
   ----- ---------------------------------- 2.1/15.1 MB 140.3 kB/s eta 0:01:34
   ----- ---------------------------------- 2.1/15.1 MB 140.3 kB/s eta 0:01:34
   ----- ---------------------------------- 2.1/15.1 MB 140.3 kB/s eta 0:01:34
   ----- ---------------------------------- 2.1/15.1 MB 140.3 kB/s eta 0:01:34
   ----- ---------------------------------- 2.1/15.1 MB 140.3 kB/s eta 0:01:34
   ----- ---------------------------------- 2.1/15.1 MB 140.3 kB/s eta 0:01:34
   ----- ---------------------------------- 2.1/15.1 MB 140.3 kB/s eta 0:01:34
   ----- ---------------------------------- 2.1/15.1 MB 140.3 kB/s eta 0:01:34
   ------ --------------------------------- 2.4/15.1 MB 139.8 kB/s eta 0:01:32
   ------ --------------------------------- 2.4/15.1 MB 139.8 kB/s eta 0:01:32
   ------ --------------------------------- 2.4/15.1 MB 139.8 kB/s eta 0:01:32
   ------ --------------------------------- 2.4/15.1 MB 139.8 kB/s eta 0:01:32
   ------ --------------------------------- 2.4/15.1 MB 139.8 kB/s eta 0:01:32
   ------ --------------------------------- 2.4/15.1 MB 139.8 kB/s eta 0:01:32
   ------ --------------------------------- 2.4/15.1 MB 139.8 kB/s eta 0:01:32
   ------ --------------------------------- 2.4/15.1 MB 139.8 kB/s eta 0:01:32
   ------ --------------------------------- 2.6/15.1 MB 141.5 kB/s eta 0:01:29
   ------ --------------------------------- 2.6/15.1 MB 141.5 kB/s eta 0:01:29
   ------ --------------------------------- 2.6/15.1 MB 141.5 kB/s eta 0:01:29
   ------ --------------------------------- 2.6/15.1 MB 141.5 kB/s eta 0:01:29
   ------ --------------------------------- 2.6/15.1 MB 141.5 kB/s eta 0:01:29
   ------ --------------------------------- 2.6/15.1 MB 141.5 kB/s eta 0:01:29
   ------- -------------------------------- 2.9/15.1 MB 145.4 kB/s eta 0:01:25
   ------- -------------------------------- 2.9/15.1 MB 145.4 kB/s eta 0:01:25
   ------- -------------------------------- 2.9/15.1 MB 145.4 kB/s eta 0:01:25
   ------- -------------------------------- 2.9/15.1 MB 145.4 kB/s eta 0:01:25
   ------- -------------------------------- 2.9/15.1 MB 145.4 kB/s eta 0:01:25
   ------- -------------------------------- 2.9/15.1 MB 145.4 kB/s eta 0:01:25
   ------- -------------------------------- 2.9/15.1 MB 145.4 kB/s eta 0:01:25
   ------- -------------------------------- 2.9/15.1 MB 145.4 kB/s eta 0:01:25
   -------- ------------------------------- 3.1/15.1 MB 146.6 kB/s eta 0:01:22
   -------- ------------------------------- 3.1/15.1 MB 146.6 kB/s eta 0:01:22
   -------- ------------------------------- 3.1/15.1 MB 146.6 kB/s eta 0:01:22
   -------- ------------------------------- 3.1/15.1 MB 146.6 kB/s eta 0:01:22
   -------- ------------------------------- 3.1/15.1 MB 146.6 kB/s eta 0:01:22
   -------- ------------------------------- 3.1/15.1 MB 146.6 kB/s eta 0:01:22
   -------- ------------------------------- 3.1/15.1 MB 146.6 kB/s eta 0:01:22
   -------- ------------------------------- 3.1/15.1 MB 146.6 kB/s eta 0:01:22
   -------- ------------------------------- 3.1/15.1 MB 146.6 kB/s eta 0:01:22
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   -------- ------------------------------- 3.4/15.1 MB 146.2 kB/s eta 0:01:21
   --------- ------------------------------ 3.7/15.1 MB 143.0 kB/s eta 0:01:21
   --------- ------------------------------ 3.7/15.1 MB 143.0 kB/s eta 0:01:21
   --------- ------------------------------ 3.7/15.1 MB 143.0 kB/s eta 0:01:21
   --------- ------------------------------ 3.7/15.1 MB 143.0 kB/s eta 0:01:21
   --------- ------------------------------ 3.7/15.1 MB 143.0 kB/s eta 0:01:21
   --------- ------------------------------ 3.7/15.1 MB 143.0 kB/s eta 0:01:21
   --------- ------------------------------ 3.7/15.1 MB 143.0 kB/s eta 0:01:21
   --------- ------------------------------ 3.7/15.1 MB 143.0 kB/s eta 0:01:21
   ---------- ----------------------------- 3.9/15.1 MB 144.1 kB/s eta 0:01:18
   ---------- ----------------------------- 3.9/15.1 MB 144.1 kB/s eta 0:01:18
   ---------- ----------------------------- 3.9/15.1 MB 144.1 kB/s eta 0:01:18
   ---------- ----------------------------- 3.9/15.1 MB 144.1 kB/s eta 0:01:18
   ---------- ----------------------------- 3.9/15.1 MB 144.1 kB/s eta 0:01:18
   ---------- ----------------------------- 3.9/15.1 MB 144.1 kB/s eta 0:01:18
   ---------- ----------------------------- 3.9/15.1 MB 144.1 kB/s eta 0:01:18
   ----------- ---------------------------- 4.2/15.1 MB 145.3 kB/s eta 0:01:16
   ----------- ---------------------------- 4.2/15.1 MB 145.3 kB/s eta 0:01:16
   ----------- ---------------------------- 4.2/15.1 MB 145.3 kB/s eta 0:01:16
   ----------- ---------------------------- 4.2/15.1 MB 145.3 kB/s eta 0:01:16
   ----------- ---------------------------- 4.2/15.1 MB 145.3 kB/s eta 0:01:16
   ----------- ---------------------------- 4.2/15.1 MB 145.3 kB/s eta 0:01:16
   ----------- ---------------------------- 4.2/15.1 MB 145.3 kB/s eta 0:01:16
   ----------- ---------------------------- 4.5/15.1 MB 147.7 kB/s eta 0:01:13
   ----------- ---------------------------- 4.5/15.1 MB 147.7 kB/s eta 0:01:13
   ----------- ---------------------------- 4.5/15.1 MB 147.7 kB/s eta 0:01:13
   ----------- ---------------------------- 4.5/15.1 MB 147.7 kB/s eta 0:01:13
   ------------ --------------------------- 4.7/15.1 MB 152.0 kB/s eta 0:01:09
   ------------ --------------------------- 4.7/15.1 MB 152.0 kB/s eta 0:01:09
   ------------ --------------------------- 4.7/15.1 MB 152.0 kB/s eta 0:01:09
   ------------ --------------------------- 4.7/15.1 MB 152.0 kB/s eta 0:01:09
   ------------ --------------------------- 4.7/15.1 MB 152.0 kB/s eta 0:01:09
   ------------- -------------------------- 5.0/15.1 MB 163.3 kB/s eta 0:01:03
   ------------- -------------------------- 5.0/15.1 MB 163.3 kB/s eta 0:01:03
   ------------- -------------------------- 5.0/15.1 MB 163.3 kB/s eta 0:01:03
   ------------- -------------------------- 5.0/15.1 MB 163.3 kB/s eta 0:01:03
   ------------- -------------------------- 5.0/15.1 MB 163.3 kB/s eta 0:01:03
   ------------- -------------------------- 5.0/15.1 MB 163.3 kB/s eta 0:01:03
   ------------- -------------------------- 5.2/15.1 MB 165.5 kB/s eta 0:01:00
   ------------- -------------------------- 5.2/15.1 MB 165.5 kB/s eta 0:01:00
   ------------- -------------------------- 5.2/15.1 MB 165.5 kB/s eta 0:01:00
   ------------- -------------------------- 5.2/15.1 MB 165.5 kB/s eta 0:01:00
   ------------- -------------------------- 5.2/15.1 MB 165.5 kB/s eta 0:01:00
   ------------- -------------------------- 5.2/15.1 MB 165.5 kB/s eta 0:01:00
   -------------- ------------------------- 5.5/15.1 MB 167.8 kB/s eta 0:00:58
   -------------- ------------------------- 5.5/15.1 MB 167.8 kB/s eta 0:00:58
   -------------- ------------------------- 5.5/15.1 MB 167.8 kB/s eta 0:00:58
   -------------- ------------------------- 5.5/15.1 MB 167.8 kB/s eta 0:00:58
   -------------- ------------------------- 5.5/15.1 MB 167.8 kB/s eta 0:00:58
   --------------- ------------------------ 5.8/15.1 MB 175.5 kB/s eta 0:00:54
   --------------- ------------------------ 5.8/15.1 MB 175.5 kB/s eta 0:00:54
   --------------- ------------------------ 5.8/15.1 MB 175.5 kB/s eta 0:00:54
   --------------- ------------------------ 5.8/15.1 MB 175.5 kB/s eta 0:00:54
   --------------- ------------------------ 5.8/15.1 MB 175.5 kB/s eta 0:00:54
   --------------- ------------------------ 5.8/15.1 MB 175.5 kB/s eta 0:00:54
   --------------- ------------------------ 6.0/15.1 MB 177.0 kB/s eta 0:00:52

# LIBRERIA SDV
# Autor: Fernanda Pacheco Banda
# Fecha: 04 de junio

In [1]:
#Importamos Librerias
import pandas as pd
import numpy as np
import random

In [2]:
import sdv #Generar datos sinteticos
import sdmetrics #Evaluar la calidad de los datos
from sdv.metadata import SingleTableMetadata
from sdv.single_table import GaussianCopulaSynthesizer

In [3]:
from sdmetrics.reports.single_table import QualityReport

In [4]:
print ("SDV:", sdv.__version__)

SDV: 1.37.0

In [5]:
#Creamos un dataset original que servira como fuente para crear los datos sinteticos
dfClientes = pd.DataFrame(
    {
        "cliente_id": [1,2,3,4,5,6,7,8,9,10],
        "edad": [23,33,43,28,53,56,65,40,25,46],
        "ingreso_mensual": [25000,15000,20000,10000,5000,17000,30000,12000,35000,7500],
        "ciudad": ["Veracruz","Cordoba","Paso del Macho","Amatlan","Fortin","Cuitlahuac","Yanga","Cordoba","Orizaba","Cuitlahuac"]
    }
)

In [6]:
dfClientes.head()

   cliente_id  edad  ingreso_mensual          ciudad
0           1    23            25000        Veracruz
1           2    33            15000         Cordoba
2           3    43            20000  Paso del Macho
3           4    28            10000         Amatlan
4           5    53             5000          Fortin

In [7]:
#Definir los metadatos
metadata = SingleTableMetadata()

In [8]:
metadata.detect_from_dataframe(
    data = dfClientes
)

In [ ]:
metadata.visualize()

In [10]:
metadata.to_dict()

{'primary_key': 'cliente_id',
 'METADATA_SPEC_VERSION': 'SINGLE_TABLE_V1',
 'columns': {'cliente_id': {'sdtype': 'id'},
  'edad': {'sdtype': 'numerical'},
  'ingreso_mensual': {'sdtype': 'numerical'},
  'ciudad': {'sdtype': 'categorical'}}}

In [ ]:
#
metadata.save_to_json(
    "dfClientes_metadata.json"
)

In [12]:
#Entrenamos el modelo para generar los datos sinteticos
synthesizer = GaussianCopulaSynthesizer(
    metadata
)

C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages\sdv\single_table\base.py:182: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages\sdv\single_table\base.py:138: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(
Task was destroyed but it is pending!
task: <Task pending name='Task-102' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-103' coro=<Kernel.shell_main() running at C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.task_wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages\zmq\eventloop\zmqstream.py:563]>
C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\copy.py:238: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  return type(x)(x.__func__, deepcopy(x.__self__, memo))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-103' coro=<Kernel.shell_main() running at C:\Users\pache\anaconda3\envs\Extraccion-9BESC\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.task_wakeup()]>

In [13]:
#Entrenamiento 
synthesizer.fit(
    dfClientes
)

In [14]:
#Generamos los datos sinteticos
clientes_sinteticos = synthesizer.sample(
    num_rows=100
)

In [15]:
clientes_sinteticos.head()

   cliente_id  edad  ingreso_mensual   ciudad
0    16169768    48            13388  Cordoba
1     4918803    48            20305    Yanga
2     1900081    35            20376  Amatlan
3      531516    33            17474    Yanga
4    10211768    51            10877  Amatlan

In [16]:
clientes_sinteticos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cliente_id       100 non-null    int64
 1   edad             100 non-null    int64
 2   ingreso_mensual  100 non-null    int64
 3   ciudad           100 non-null    object
dtypes: int64(3), object(1)
memory usage: 3.3+ KB

In [18]:
clientes_sinteticos.describe(include="all")

          cliente_id        edad  ingreso_mensual   ciudad
count   1.000000e+02  100.000000       100.000000      100
unique           NaN         NaN              NaN        8
top              NaN         NaN              NaN  Cordoba
freq             NaN         NaN              NaN       30
mean    8.532170e+06   42.570000     22582.030000      NaN
std     4.687773e+06   11.737237      8954.955259      NaN
min     4.660500e+04   25.000000      5951.000000      NaN
25%     5.008268e+06   32.000000     15070.750000      NaN
50%     8.656048e+06   42.000000     21953.000000      NaN
75%     1.256688e+07   51.500000     31727.250000      NaN
max     1.661551e+07   65.000000     34991.000000      NaN

In [19]:
#DataFrame contaminado
dfClientesGIGO = clientes_sinteticos.copy()

In [20]:
#Colocar edades imposibles
indices = random.sample(list(dfClientesGIGO.index),5)

In [22]:
dfClientesGIGO.loc[indices,"edad"]= -5

In [23]:
#Introducimos valores duplicados
duplicados = dfClientesGIGO.sample(10,random_state=42)

In [24]:
dfClientesGIGO = pd.concat([dfClientesGIGO,duplicados], ignore_index=True)

In [30]:
#Verificamos valores nulos
dfClientesGIGO.duplicated().sum()

np.int64(10)

In [34]:
dfClientesGIGO.describe(include="all")

          cliente_id        edad  ingreso_mensual   ciudad
count   1.100000e+02  110.000000       110.000000      110
unique           NaN         NaN              NaN        8
top              NaN         NaN              NaN  Cordoba
freq             NaN         NaN              NaN       32
mean    8.614045e+06   39.554545     23205.372727      NaN
std     4.775996e+06   15.302807      8989.560842      NaN
min     4.660500e+04   -5.000000      5951.000000      NaN
25%     4.948624e+06   29.000000     16088.000000      NaN
50%     8.956428e+06   39.000000     22874.000000      NaN
75%     1.274153e+07   51.000000     32271.500000      NaN
max     1.661551e+07   65.000000     34991.000000      NaN

In [37]:
#Generamos el reporte
reporte = QualityReport()

In [39]:
reporte.generate(
    real_data = dfClientes,
    synthetic_data = clientes_sinteticos,
    metadata = metadata.to_dict()
)

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 4/4 [00:00<00:00, 244.92it/s]|
Column Shapes Score: 78.0%

(2/2) Evaluating Column Pair Trends: |██████████| 6/6 [00:00<00:00, 87.93it/s]|
Column Pair Trends Score: 10.0%

Overall Score (Average): 44.0%

In [40]:
reporte.generate(
    real_data = dfClientes,
    synthetic_data = dfClientesGIGO,
    metadata = metadata.to_dict()
)

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 4/4 [00:00<00:00, 453.71it/s]|
Column Shapes Score: 77.88%

(2/2) Evaluating Column Pair Trends: |██████████| 6/6 [00:00<00:00, 147.89it/s]|
Column Pair Trends Score: 13.18%

Overall Score (Average): 45.53%